FROM frolvlad/alpine-oraclejdk8:slim
VOLUME /tmp
ADD dgcCardService-0.0.1.jar dgcCardService.jar
RUN sh -c 'touch /dgcCardService.jar'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /dgcCardService.jar" ]